const REACT_APP_PUBLIC_APP_ENV = process.env.REACT_APP_PUBLIC_APP_ENV;
const REACT_APP_PUBLIC_ARENT_DOMAIN = process.env.REACT_APP_PUBLIC_ARENT_DOMAIN;


export { REACT_APP_PUBLIC_ARENT_DOMAIN, REACT_APP_PUBLIC_APP_ENV };
